name: radio
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  video_player: ^2.9.2
  just_audio: ^0.9.28
  carousel_slider: ^4.2.0
  share_plus: ^7.2.2
  google_fonts: ^5.0.0
  youtube_player_flutter: ^9.1.1
  cached_network_image: ^3.3.1
  firebase_core: ^3.8.1
  cupertino_icons: ^1.0.8
  mime: ^1.0.5
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logov.mp4
    - assets/logo.png
    - assets/song.mp3
    - assets/dilj.jpg
    - assets/hk.jpg
    - assets/knika.jpg
    - assets/shm.jpg
    - assets/jordan.jpg
    - assets/nk.jpg
    - assets/stree.jpg
    - assets/million.jpg
    - assets/rt.jpg
    - assets/nat.jpg
    - assets/peg.jpg
    - assets/bhul.jpg
    - assets/ka.jpg
    - assets/sush.png
    - assets/gru.jpg
    - assets/hny.jpg
    - assets/sdu.webp
    - assets/bu.jpg
    - assets/app.jpeg
    - assets/amg.webp
